# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Radio Pi
tagline:          An easy way to stream!
url:              http://radio-pi.github.io
paginate:         1
baseurl:          /
author:
  name:           Sir l33tname
  url:            https://l33t.name
  email:          hi@l33t.name
